<a href="https://colab.research.google.com/github/kjapan87/RNN_Model_V1/blob/main/Recurrent_Neural_Network_Example_(churn_model).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
MainData = pd.read_csv("Churn_Modelling.csv")

In [ ]:
y = MainData.iloc[0:10000,-1].values
x = MainData.iloc[0:10000,3:13].values

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
x[:,2] = label.fit_transform(x[:,2])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
colT = ColumnTransformer([("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x = np.array(colT.fit_transform(x))


In [ ]:
from sklearn.model_selection import train_test_split #data and splitting in training & testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,train_size = 0.70,random_state = 0) 


In [ ]:

from sklearn.preprocessing import StandardScaler
scal =  StandardScaler()
x_train = scal.fit_transform(x_train)


In [ ]:
print(x_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [1.0 0.0 0.0 ... 1 1 167400.29]
 [1.0 0.0 0.0 ... 1 1 70849.47]
 [0.0 1.0 0.0 ... 1 1 33759.41]]


In [ ]:
x_test = scal.transform(x_test)

In [ ]:
print(x_test)

[[-1.01525927  1.75478035 -0.5731713  ...  0.64198477  0.96683535
   1.61245299]
 [ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477 -1.03430227
   0.49796226]
 [-1.01525927 -0.56987189  1.74467913 ...  0.64198477  0.96683535
  -0.42228531]
 ...
 [ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477  0.96683535
   1.17026765]
 [ 0.98497008 -0.56987189 -0.5731713  ...  0.64198477  0.96683535
  -0.50711407]
 [-1.01525927  1.75478035 -0.5731713  ...  0.64198477  0.96683535
  -1.15148134]]


In [ ]:
#ANN 
import tensorflow as tf
from tensorflow.keras.models import Sequential
model = Sequential()

In [ ]:
from tensorflow.keras.layers import Dense
model.add(Dense(units=64, input_dim=12, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=1, activation='softmax'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
219/219 [==============================] - 0s 1ms/step - loss: 12.1645 - accuracy: 0.2023
Epoch 2/5
219/219 [==============================] - 0s 1ms/step - loss: 12.1645 - accuracy: 0.2023
Epoch 3/5
219/219 [==============================] - 0s 1ms/step - loss: 12.1645 - accuracy: 0.2023
Epoch 4/5
219/219 [==============================] - 0s 1ms/step - loss: 12.1645 - accuracy: 0.2023
Epoch 5/5
219/219 [==============================] - 0s 1ms/step - loss: 12.1645 - accuracy: 0.2023


In [ ]:
loss_and_metrics = model.evaluate(x_test, y_test, batch_size=128)
classes = model.predict(x_test)

24/24 [==============================] - 0s 1ms/step - loss: 12.0926 - accuracy: 0.2070


In [ ]:
x_test

array([[-1.01525927,  1.75478035, -0.5731713 , ...,  0.64198477,
         0.96683535,  1.61245299],
       [ 0.98497008, -0.56987189, -0.5731713 , ...,  0.64198477,
        -1.03430227,  0.49796226],
       [-1.01525927, -0.56987189,  1.74467913, ...,  0.64198477,
         0.96683535, -0.42228531],
       ...,
       [ 0.98497008, -0.56987189, -0.5731713 , ...,  0.64198477,
         0.96683535,  1.17026765],
       [ 0.98497008, -0.56987189, -0.5731713 , ...,  0.64198477,
         0.96683535, -0.50711407],
       [-1.01525927,  1.75478035, -0.5731713 , ...,  0.64198477,
         0.96683535, -1.15148134]])

In [ ]:
MainData.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
x.shape

(10000, 12)

In [ ]:
X_ques=[[1,0,1,200,0,40,10,400,1,0,1,1900]]
classe2=model.predict(X_ques)

In [ ]:
classe2

array([[1.]], dtype=float32)

In [ ]:
classes = model.predict(x_test)
classes = (classes > 0.5)
print(np.concatenate((classes.reshape(len(classes),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 1]]


In [ ]:
print(classes)

[[ True]
 [ True]
 [ True]
 ...
 [ True]
 [ True]
 [ True]]


In [ ]:
print(loss_and_metrics)

[12.092645645141602, 0.2070000022649765]


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
report = classification_report(y_test,classes)
conf = confusion_matrix(y_test, classes)
print(conf)
print(report)

[[   0 2379]
 [   0  621]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      2379
           1       0.21      1.00      0.34       621

    accuracy                           0.21      3000
   macro avg       0.10      0.50      0.17      3000
weighted avg       0.04      0.21      0.07      3000



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
